In [1]:
import json
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely import wkt
from shapely.ops import unary_union

from pathlib import Path
from tqdm.auto import tqdm

datasets = Path("/nas/cee-ice/data")

save_dir = Path("/nas/cee-water/cjgleason/ted/swot-ml/data/owen_reservoirs/Columbia")
metadata_dir = save_dir / "metadata"

subbasins = gpd.read_parquet(metadata_dir / 'subbasins_4km2.parquet')
subbasins.index = subbasins.index.astype(str)
subbasins.geometry = subbasins.geometry.centroid
footprint_geom = unary_union(subbasins.geometry.envelope)

/tmp/ipykernel_3708119/2484409471.py:18: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  subbasins.geometry = subbasins.geometry.centroid

In [3]:
# Read in hydroatlas
gdb_path = datasets / "HydroSHEDS" / "HydroATLAS" / "BasinATLAS_v10.gdb"
layer_name = "BasinATLAS_v10_lev09"

hydroatlas = gpd.read_file(gdb_path, layer=layer_name, engine="pyogrio", use_arrow=True)
hydroatlas.replace({'wet_cl_smj':-9999}, 13, inplace=True)
hydroatlas = hydroatlas.set_index('HYBAS_ID')

# hydroatlas_filt = hydroatlas[hydroatlas.intersects(footprint_geom)]
# hydroatlas_filt

/nas/cee-water/cjgleason/ted/swot-ml/.venv/lib/python3.11/site-packages/pyogrio/raw.py:337: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
  table = reader.read_all()

In [5]:
# hydroatlas_filt = hydroatlas[hydroatlas.intersects(footprint_geom)]
# hydroatlas_filt

In [14]:
hybas_pairs.index

Index(['23021321', '23021261', '23021244', '23021122', '23021112', '23021112',
       '23021045', '23018471', '23014554', '23014554',
       ...
       'USGS-15908000', 'USGS-15908000', 'USGS-15908000', 'USGS-15908000',
       'USGS-15908000', 'USGS-15905100', 'USGS-15905100', 'USGS-15905100',
       'USGS-15905100', 'USGS-15905100'],
      dtype='object', name='site_id', length=112790)

In [7]:
subs_buff = subbasins.copy()
subs_buff = subs_buff.to_crs("EPSG:6933")
subs_buff.geometry = subs_buff.buffer(2500)

hybas_pairs = gpd.sjoin(
    subs_buff,
    hydroatlas.to_crs("EPSG:6933"),
    how='left',
)

hybas_area = hybas_pairs['UP_AREA']
merit_area = hybas_pairs['uparea_km2']
hybas_pairs['hybas_area_diff'] = (hybas_area - merit_area) / ((hybas_area + merit_area)/2)

def get_best_hybas(grp):
     # Pick best match by area.
    idx_min = grp['hybas_area_diff'].abs().idxmin()
    return grp.loc[idx_min]

all_attributes = hybas_pairs.reset_index().groupby('site_id').apply(get_best_hybas, include_groups=False)

In [8]:
all_attributes

,geometry,area_km2,uparea_km2,original_comid,node_type,is_gauge,is_reservoir,nextdown,outlet_id,HYBAS_ID,...,hft_ix_s09,hft_ix_u09,gad_id_smj,gdp_ud_sav,gdp_ud_ssu,gdp_ud_usu,hdi_ix_sav,Shape_Length,Shape_Area,hybas_area_diff
site_id,,,,,,,,,,,,,,,,,,,,,
78007101,"POLYGON ((-11397970.627 5802126.689, -11397982...",187.878281,674.934996,78007101,original,False,False,7820071213,USGS-14246900,7.090223e+09,...,0,0,41,41815,1.465360e+05,3.770672e+05,924,1.604932,0.070765,0.360948
78007191,"POLYGON ((-11374665.52 5802166.538, -11374677....",487.056715,487.056715,78007191,original,False,False,78007101,USGS-14246900,7.090218e+09,...,0,0,41,46472,6.906823e+03,6.906823e+03,924,0.991235,0.034850,-0.597093
78007214,"POLYGON ((-11511746.018 5833993.619, -11511758...",61.349363,366.835934,78007214,split_downstream,False,False,7820071213,USGS-14246900,7.090208e+09,...,3,3,41,41007,3.155499e+06,3.155500e+06,923,1.267565,0.049119,0.002625
78007257,"POLYGON ((-11423353.344 5810576.113, -11423365...",490.765797,490.765797,78007257,original,False,False,7820071213,USGS-14246900,7.090216e+09,...,0,0,41,41792,3.898186e+05,3.898184e+05,923,1.584513,0.084067,0.253760
78007356,"POLYGON ((-11371774.079 5785242.409, -11371786...",154.550897,154.550897,78007356,original,False,False,7820071213,USGS-14246900,7.090228e+09,...,1,1,41,41007,3.531842e+04,3.531842e+04,923,1.003827,0.034359,0.513401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USGS-14236200,"POLYGON ((-11796590.997 5323778.293, -11796603...",356.139032,356.139032,78018213,gauge,True,False,7820030793,USGS-14246900,7.090369e+09,...,56,56,240,55867,1.459517e+08,1.459517e+08,948,1.372121,0.047163,0.117755
USGS-14238000,"POLYGON ((-11827088.717 5315505.174, -11827100...",4.076160,3598.232776,78017902,gauge,True,False,78017892,USGS-14246900,7.090370e+09,...,115,30,240,55867,3.761161e+07,6.212481e+08,948,0.232961,0.002844,-0.040210
USGS-14242580,"POLYGON ((-11820960.356 5293463.373, -11820972...",431.403474,1293.566256,78017968,gauge,True,False,USGS-14243000,USGS-14246900,7.090374e+09,...,25,25,240,55867,6.733032e+06,6.733031e+06,948,1.267044,0.043682,-1.104374
USGS-14243000,"POLYGON ((-11858562.85 5308948.42, -11858574.8...",470.317506,5767.696618,78017888,gauge,True,False,78017886,USGS-14246900,7.090374e+09,...,107,35,240,55867,1.598642e+08,1.169639e+09,948,0.754285,0.014555,-0.328737
USGS-14246900,"POLYGON ((-11876856.819 5290328.045, -11876868...",375.176233,651408.057898,78017389,gauge,True,False,None,USGS-14246900,7.090380e+09,...,127,42,240,53750,1.984572e+09,3.897060e+11,945,1.250759,0.051750,-0.001316

In [9]:
attributes_dir = save_dir / 'attributes' 
attributes_dir.mkdir(parents=True, exist_ok=True)

In [10]:
hybas_properties = pd.read_csv(attributes_dir / "properties.txt", header=None)[0].to_list()
matchup_props = ['outlet_id', 'area_km2','uparea_km2']
all_props = matchup_props + hybas_properties + ['hybas_area_diff']

In [11]:
attributes = (
    all_attributes[all_props]
    .reset_index()
    .rename(columns={'site_id':'subbasin', 'outlet_id': 'basin'})
    .astype({'subbasin':str, 'basin': str})
    .set_index(['basin', 'subbasin'])
)
attributes

                               area_km2     uparea_km2   dis_m3_pyr  \
basin         subbasin
USGS-14246900 78007101       187.878281     674.934996    24.731001
              78007191       487.056715     487.056715     4.498000
              78007214        61.349363     366.835934     9.646000
              78007257       490.765797     490.765797    17.368000
              78007356       154.550897     154.550897     7.621000
...                                 ...            ...          ...
              USGS-14236200  356.139032     356.139032    16.018999
              USGS-14238000    4.076160    3598.232776   166.397003
              USGS-14242580  431.403474    1293.566256    18.171000
              USGS-14243000  470.317506    5767.696618   188.699005
              USGS-14246900  375.176233  651408.057898  7525.879883

                              dis_m3_pmn    dis_m3_pmx  run_mm_syr  \
basin         subbasin
USGS-14246900 78007101          2.059000     78.717003         946
              78007191          0.335000     18.511999         656
              78007214          1.192000     29.046000         813
              78007257          1.735000     53.702999         848
              78007356          0.555000     26.520000        1011
...                                  ...           ...         ...
              USGS-14236200     3.701000     27.525000        1316
              USGS-14238000    47.576000    288.132996        1192
              USGS-14242580     4.211000     30.427999        1536
              USGS-14243000    54.316002    325.016998        1152
              USGS-14246900  3936.400879  13796.940430        1309

                             inu_pc_smn  inu_pc_smx  inu_pc_slt  lka_pc_sse  \
basin         subbasin
USGS-14246900 78007101                6           6           8          64
              78007191                3           4           6          33
              78007214                3           3           3           0
              78007257                0           0           0           3
              78007356                5           5          11          17
...                                 ...         ...         ...         ...
              USGS-14236200           0           0           1           2
              USGS-14238000           0           5          16         176
              USGS-14242580           0           1           2          32
              USGS-14243000           8          14          21           0
              USGS-14246900          13          21          24           0

                             ...  urb_pc_sse  nli_ix_sav  rdd_mk_sav  \
basin         subbasin       ...
USGS-14246900 78007101       ...           0           0           0
              78007191       ...           0           0           0
              78007214       ...           0           8          13
              78007257       ...           0           0           0
              78007356       ...           0           0           0
...                          ...         ...         ...         ...
              USGS-14236200  ...           0         392         111
              USGS-14238000  ...           0         741         268
              USGS-14242580  ...           0          96         141
              USGS-14243000  ...           0         951         416
              USGS-14246900  ...           9        1669         735

                             hft_ix_s93  hft_ix_s09  gad_id_smj  gdp_ud_sav  \
basin         subbasin
USGS-14246900 78007101                0           0          41       41815
              78007191                0           0          41       46472
              78007214                3           3          41       41007
              78007257                0           0          41       41792
              78007356                1           1          41       41007
...                                 ...         ...         ...         ...
              USGS-14236200          58          56         240       55867
              USGS-14238000         119         115         240       55867
              USGS-14242580          27          25         240       55867
              USGS-14243000         120         107         240       55867
              USGS-14246900         129         127         240       53750

                               gdp_ud_ssu  hdi_ix_sav  hybas_area_diff
basin         subbasin
USGS-14246900 78007101       1.465360e+05         924         0.360948
              78007191       6.906823e+03         924        -0.597093
              78007214       3.155499e+06         923         0.002625
              78007257       3.898186e+05         923         0.253760
              78007356       3.531842e+04         923         0.513401
...                                   ...         ...              ...
              USGS-14236200  1.459517e+08         948         0.117755
              USGS-14238000  3.761161e+07         948        -0.040210
              USGS-14242580  6.733032e+06         948        -1.104374
              USGS-14243000  1.598642e+08         948        -0.328737
              USGS-14246900  1.984572e+09         945        -0.001316

[2144 rows x 197 columns]

In [12]:
attributes.to_parquet(attributes_dir / f"static_4km2.parquet")

In [36]:
test = pd.read_parquet(attributes_dir / "static.parquet")

In [37]:
test

                               area_km2   uparea_km2  dis_m3_pyr  dis_m3_pmn  \
basin         subbasin
EAUF-V7200010 21000002       468.102025  4364.328752   66.342003   22.684999
              21000020       401.905725  3625.201976   48.854000   16.743000
              21000022       292.309508  3076.492166   28.339001    9.780000
              21000026       481.039377  1767.807919    6.031000    2.077000
              21000032       390.920772   621.770285    8.653000    3.024000
...                                 ...          ...         ...         ...
USGS-50129254 USGS-50129254   42.674493    42.674493    4.198000    1.576000
USGS-50138000 USGS-50136400   51.402873    51.402873    0.185000    0.068000
              USGS-50138000  261.453879   312.856752    5.788000    2.068000
USGS-50144000 USGS-50144000  349.557308   349.557308    9.208000    3.183000
USGS-50147800 USGS-50147800  195.872993   195.872993    5.115000    1.855000

                             dis_m3_pmx  run_mm_syr  inu_pc_smn  inu_pc_smx  \
basin         subbasin
EAUF-V7200010 21000002       108.996002         525           0           0
              21000020        80.602997         537           0           0
              21000022        46.625000         504           0           0
              21000026         9.826000         422           0           0
              21000032        14.126000         437           0           0
...                                 ...         ...         ...         ...
USGS-50129254 USGS-50129254    8.597000         578          61          69
USGS-50138000 USGS-50136400    0.359000         598          63          79
              USGS-50138000   11.577000         593          30          48
USGS-50144000 USGS-50144000   19.839001         609          36          61
USGS-50147800 USGS-50147800   10.214000         601          26          38

                             inu_pc_slt  lka_pc_sse  ...  urb_pc_sse  \
basin         subbasin                               ...
EAUF-V7200010 21000002                1           0  ...           0
              21000020                0           0  ...           0
              21000022                0           1  ...           0
              21000026                0           0  ...           0
              21000032                0           0  ...           0
...                                 ...         ...  ...         ...
USGS-50129254 USGS-50129254          72           1  ...          22
USGS-50138000 USGS-50136400          80           0  ...          48
              USGS-50138000          51           0  ...          27
USGS-50144000 USGS-50144000          62           1  ...           4
USGS-50147800 USGS-50147800          38           0  ...          39

                             nli_ix_sav  rdd_mk_sav  hft_ix_s93  hft_ix_s09  \
basin         subbasin
EAUF-V7200010 21000002              844         711         135         106
              21000020             1754         786         187         163
              21000022              842         631         133          88
              21000026              728         759         142          92
              21000032              824         536         127          86
...                                 ...         ...         ...         ...
USGS-50129254 USGS-50129254        3209        2365         296         277
USGS-50138000 USGS-50136400        4778        5447         363         346
              USGS-50138000        3680        2432         291         288
USGS-50144000 USGS-50144000        1686        1292         222         173
USGS-50147800 USGS-50147800        3856        1703         301         286

                             gad_id_smj  gdp_ud_sav    gdp_ud_ssu  hdi_ix_sav  \
basin         subbasin
EAUF-V7200010 21000002               79       29174  3.976704e+08         910
              21000020               79       29174  1.899765e+08         910
              21000022               79       29174  1.372329e+08         910
              21000026               79       30484  2.234216e+08         899
              21000032               79       28545  2.993196e+08         902
...                                 ...         ...           ...         ...
USGS-50129254 USGS-50129254         181       34887  1.574034e+09         832
USGS-50138000 USGS-50136400         181       34887  1.705076e+09         832
              USGS-50138000         181       34887  3.784680e+09         832
USGS-50144000 USGS-50144000         181       34887  1.818283e+09         832
USGS-50147800 USGS-50147800         181       34887  3.385777e+09         832

                             hybas_area_diff
basin         subbasin
EAUF-V7200010 21000002             -0.059877
              21000020             -0.164848
              21000022             -0.440938
              21000026             -1.183507
              21000032              0.015052
...                                      ...
USGS-50129254 USGS-50129254         1.339595
USGS-50138000 USGS-50136400         0.288039
              USGS-50138000         0.085791
USGS-50144000 USGS-50144000         0.295377
USGS-50147800 USGS-50147800         0.399315

[72193 rows x 197 columns]